### ISSUE TITLE
BIOS/GS Options never remembered.

### ISSUE THREAD

**Issue by DjBlades** [Spectabis/WPF_Spectabis#11]
Heyo, I've only really just started using Spectabis/PCSX2, so I have no idea if this is my fault or not, but I have a problem whenever I start a game without first "setting it up" so to speak.
If I try to run a game, PCSX2 will immediately throw an error that my GS Plugin doesn't exist, as it's searching in "C:\Users\James\LaunchBox\Emulators\Spectabis\PCSX2\plugins\Please Configure", the same for my BIOS file. I have to use the "Configure in PCSX2" option and set these paths again for each game before I am able to properly play it.
Is this intended behavior, hence the Please Configure, or am I missing an option to change somewhere within Spectabis?

**Comment by FaithLV** [comment]
It's something I can't really fix.

You have to open PCSX2 once outside Spectabis and configure the settings, because Spectabis copies settings from PCSX2 configuration.

**Comment by DjBlades** [comment]
I've got the GS and BIOS set up in normal PCSX2 as well, it's just every time a game is launched through Spectabis it forgets.

**Comment by SamsWrath** [comment]
I have a similar but, slightly different problem. When I try to launch a game, I receive the same error as DJBlades but, when I hit the refresh button for my BIOS, nothing comes up.

**Comment by FaithLV** [comment]
Could you please screenshot the message you're receiving?

And are you certain that you have configured and launched a game once with PCSX2, before adding a game to Spectabis?

**Comment by SamsWrath** [comment]
Thanks for the quick follow-up.

I continued to play around with the program after I posted here last night. After a bit, I received a pop-up from Spectabis saying, "PCSX2 install is corrupt." So I uninstalled PCSX2 and reinstalled and everything is working fine now.

**Comment by FaithLV** [comment]
Closing as it's been a month since OP posted and hasn't followed up.
