### ISSUE TITLE
Specifying pluginDir creates crash on start

### ISSUE THREAD

**Issue by cascardian** [Spectabis/WPF_Spectabis#2]
Entering the plugin directory path (`null` works, of course) in advanced.ini will crash Spectabis with the following error:

> 'The invocation of the constructor on type 'Spectabis_WPF.Views.MainWindow' that matches the specified binding constraints threw an exception.' Line number '15' and line position '9'.
The process cannot access the file 'E:\Emulator Games\PCSX2\\plugins\LilyPad.dll' because it is being used by another process.

No process is running that would load LilyPad.dll, so this confuses me. Have you encountered it before?

**Comment by FaithLV** [comment]
Just tested, works on my end.

Don't worry if it's not working, because it's just a one-time setup. These plugins are not used in emulator, but instead in configuration window. You can leave path as `null`.

**Comment by FaithLV** [comment]
Plugins will be shipped with Spectabis from now and won't be copied from anywhere automatically.
